<a href="https://colab.research.google.com/github/bhoop70233/computer-vision/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.4.0+cu121'

In [3]:
#Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get the python number within a tensor(only works with one - element tensor)
scalar.item()

7

In [6]:
# vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#Check the number of dimensions of vector
vector.ndim

1

In [8]:
#check shape of vector
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
#Check number of dimensions
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
#Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.0551, 0.9480, 0.0792, 0.1488],
         [0.6036, 0.8884, 0.1468, 0.1179],
         [0.0022, 0.5499, 0.4274, 0.0341]]),
 torch.float32)

In [19]:
#Create a random tensor of size(224,224,3)
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
#Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [22]:
#Use torch.arrange(),torch.range() is deprecated
zero_to_ten_deprecated=torch.range(0,10)  #Note :this may return an error in the future
#Create a range of values 0 to 10
zero_to_ten=torch.arange(start=0,end=10,step=1)
zero_to_ten

<ipython-input-22-c334314d1cb5>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated=torch.range(0,10)  #Note :this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#Can also create a tensor of zeros similar to another tensor
ten_zeros=torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#Default datatype for tensors is floats is float32
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,## defaults to None, which is torch.float32 or whatever datatype is passed
                             device=None,## defaults to None, which uses the default tensor type
                             requires_grad=False)#if True , operations performed on the tensor are recorded

float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],

                             dtype=torch.float16)# torch.half would also work
float_16_tensor.dtype


torch.float16

In [26]:
#Create a tensor
some_tensor=torch.rand(3,4)
# Find out details about it
print(some_tensor)
print(f"Shape  of tensor:{some_tensor.shape}")
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Device tensor is stored on:{some_tensor.device}") #will default to cpu

tensor([[0.9183, 0.7772, 0.1775, 0.5935],
        [0.0259, 0.9123, 0.4803, 0.0096],
        [0.0257, 0.4755, 0.5181, 0.3874]])
Shape  of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu
